name: send email report
on:
    workflow_dispatch:

jobs:
    email:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6

            - name: Setup Python
              uses: actions/setup-python@v6
              with:
                python-version: '3.12.3'

            - name: Pull latest changes
              run: |
                git config --global user.name "github-actions[bot]"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git pull --rebase origin main