name: Orchestrate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  run-investment-workflow:
    uses: ./.github/workflows/Investment.yml
  
  run-etf-workflow:
    needs: run-investment-workflow
    if: always()
    uses: ./.github/workflows/ETF.yml

  run-mf-workflow:
    needs: run-etf-workflow
    if: always()
    uses: ./.github/workflows/MF.yml