name: Scheduled Sequential Run
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  run-workflow-1:
    uses: ./.github/workflows/Investment.yml
  
  run-workflow-2:
    needs: run-workflow-1
    uses: ./.github/workflows/ETF.yml

  run-workflow-3:
    needs: run-workflow-2
    uses: ./.github/workflows/MF.yml